server
{
	listen 127.0.0.1:1234
	server_name hello_world

	root ./www
	index index.html

	location /
	{
		methods GET
	}

	location /delete 
	{
		methods DELETE 
	}

	location /post
	{
		methods POST
		upload ./upload 
	}
}