server
{
	listen 127.0.0.1:1234;
	server_name swedish_server bla blab ;;;;; something;

	max_client_body_size 500000;
	max_client_header_size 4000;
	index index.html;
	root ./www;

    error_page 403 /www/error/403.html;
    error_page 404 /www/error/404.html;
    error_page 405 /www/error/405.html;
    error_page 408 /www/error/408.html;
    error_page 409 /www/error/409.html;
    error_page 411 /www/error/411.html;
    error_page 413 /www/error/413.html;
    error_page 414 /www/error/414.html;
    error_page 415 /www/error/415.html;
    error_page 418 /www/error/418.html;
    error_page 431 /www/error/431.html;
    error_page 500 /www/error/500.html;
    error_page 501 /www/error/501.html;
    error_page 503 /www/error/503.html;
    error_page 505 /www/error/505.html;

	location / {
		methods GET;
		dir_listing on;
		cgi_path_php /usr/bin/php;
		cgi_path_python /usr/bin/python3
	}

	location /uploads/
	{
		methods PUT;
		root ./uploads;
	}

	location /cgi
	{
		methods POST;
		cgi_path_php /usr/bin/php;
		cgi_path_python /usr/bin/python3; 
	}

	location /post_body
	{
		methods POST;
	}

	location /directory/
	{
		methods GET;
		root ./YoupiBanane;
		index youpi.bad_extension;
	}
}
